title: Ronja's Shader Tutorials
description: I'm making shader tutorials for Unity aimed at beginners.
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://www.ronja-tutorials.com" # change this to the base hostname & protocol for your site

google_analytics: UA-124040112-1
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

pygments_options:
  tabsize: 4

theme: # leave it empty
future: true

# social
author: "Ronja Böhringer"
image: /thumbnail-jumbo.png
disqus:
  shortname: ronja-tutorials
twitter:
  username: TotallyRonja
ko-fi:
  username: RonjaTutorials
patreon:
  username: RonjaTutorials
#  site:
#  admins:

plugins:
  - jekyll-feed
  - jekyll-redirect-from

exclude: [/.idea, /.git]
